version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-usdc_eurc_analytics}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for future BullMQ jobs
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service
  api:
    image: ${REGISTRY:-}usdc-eurc-analytics-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-usdc_eurc_analytics}
      REDIS_URL: redis://redis:6379
      API_PORT: "3001"
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Indexer Service
  indexer:
    image: ${REGISTRY:-}usdc-eurc-analytics-indexer:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.indexer
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-usdc_eurc_analytics}
      REDIS_URL: redis://redis:6379
      INDEXER_POLL_INTERVAL_MS: ${INDEXER_POLL_INTERVAL_MS:-12000}
      INDEXER_BATCH_SIZE: ${INDEXER_BATCH_SIZE:-1000}
      INDEXER_SYNC_DAYS: ${INDEXER_SYNC_DAYS:-7}
      # RPC URLs - REQUIRED
      RPC_ETHEREUM_SEPOLIA: ${RPC_ETHEREUM_SEPOLIA}
      RPC_ARBITRUM_SEPOLIA: ${RPC_ARBITRUM_SEPOLIA}
      RPC_BASE_SEPOLIA: ${RPC_BASE_SEPOLIA}
      RPC_POLYGON_AMOY: ${RPC_POLYGON_AMOY}
      RPC_AVALANCHE_FUJI: ${RPC_AVALANCHE_FUJI}
      RPC_OPTIMISM_SEPOLIA: ${RPC_OPTIMISM_SEPOLIA:-}
    networks:
      - backend
    deploy:
      replicas: 1  # Only 1 indexer to avoid duplicate processing
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
      - redis

  # Web Frontend
  web:
    image: ${REGISTRY:-}usdc-eurc-analytics-web:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "${WEB_PORT:-80}:80"
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - api

  # Database migrations (run once)
  db-migrate:
    image: ${REGISTRY:-}usdc-eurc-analytics-api:${TAG:-latest}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-usdc_eurc_analytics}
    networks:
      - backend
    deploy:
      replicas: 0  # Don't run by default, use docker run
      restart_policy:
        condition: none
    depends_on:
      - postgres
    command: ["npx", "drizzle-kit", "push", "--force"]

networks:
  backend:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
